name: Microjot CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: true
jobs:
  core-unit-test:
    name: Core Unit Test Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 21.x
      - name: NPM Install
        run: npm install
      - name: Run Unit Tests
        run: npm run test-core
  api-unit-test:
    name: API Unit Test Check
    runs-on: ubuntu-latest
    steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4.0.1
              with:
                node-version: 21.x
            - name: NPM Install
              run: npm install
            - name: Run Unit Tests
              run: npm run test-api